# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
    - label: Home
      # title: This is the first menu item.
      path: homepage
      class: first
    - label: Why us?
      link: '/utopia/#whyus'
    - label: Services
      link: '/utopia/#services'
    - label: Portfolio
      link: '/utopia/#portfolio'
    - label: Staff
      link: '/utopia/#staff'
    - label: The studio
      link: '/utopia/#studio'
    - label: News
      link: '#news'
    - label: Contact us
      link: '/utopia/#contact'

news:
    - label: Home
      # title: This is the first menu item.
      path: homepage
      class: first
    - label: Why us?
      link: '/utopia/#whyus'
    - label: Services
      link: '/utopia/#services'
    - label: Portfolio
      link: '/utopia/#portfolio'
    - label: Staff
      link: '/utopia/#staff'
    - label: The studio
      link: '/utopia/#studio'
    - label: News
      link: '/utopia/showcase/news'
    - label: Contact us
      link: '/utopia/#contact'
